# -*- coding: utf-8 -*-
"""Disease_Prediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ThiQAdsy-Fqm_YKzmFPwloJ8HlvGYwq

**Importing necessory libraries**
"""

import numpy as np
import pandas as pd
import math

"""**Reading DataSet containing symptoms and diseases**"""

df=pd.read_csv("./data/dataset.csv")
df['Disease']=df['Disease'].str.strip()
df.head()

"""**Describing data to understand it**"""

df.describe()

# df.info()
